version: "3.9" 
####################### Key Cloack ######################
services: 
  postgres: 
    container_name: postgres 
    image: "postgres:13.2" 
    env_file: 
      - ./database.dev.env 
    networks: 
      - auth-backend 
    volumes: 
      - ./db-data:/var/lib/postgresql/data/ 
      - ./sql:/docker-entrypoint-initdb.d/:ro 
    ports: 
      - "127.0.0.1:5432:5432" 
  pgadmin: 
    container_name: pgadmin
    image: "dpage/pgadmin4:5.1" 
    env_file: 
      - ./database.dev.env 
    ports: 
      - "127.0.0.1:5050:80" 
    networks: 
      - auth-backend 
  keycloak: 
    container_name: keycloak
    image: "jboss/keycloak:15.0.2" 
    depends_on: 
      - "postgres" 
      - "pgadmin" 
    env_file: 
      - ./keycloak.dev.env 
    ports: 
      - "38180:8080" 
      - "8787:8787" # debug port 
    # entrypoint: ["/bin/bash","-c"]
    # command: [
    #   /opt/jboss/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin --password password %%
    #   /opt/jboss/keycloak/bin/kcadm.sh update realms/master -s sslRequired=NONE"]
    networks: 
      - auth-backend 
networks: 
  auth-backend: 
    name: auth-backend 
    driver: bridge